TRIR_2023 = 
VAR SelectedMonth = SELECTEDVALUE ( mDateTable_TRIR[Month] )
VAR MinDate = DATE(2023, 1, 1)
VAR MaxDate = EOMONTH(DATE(2023, SelectedMonth, 1), 0)
RETURN
    DIVIDE (
        CALCULATE (
            SUM ( Incidents[RecordableCount] ) * 200000,
            FILTER ( ALL ( mDateTable_TRIR ), mDateTable_TRIR[Date] >= MinDate && mDateTable_TRIR[Date] <= MaxDate && YEAR(mDateTable_TRIR[Date]) = 2023 )
        ),
        CALCULATE (
            SUM ( TRIR_Hours[HoursWorked] ),
            FILTER ( ALL ( mDateTable_TRIR ), mDateTable_TRIR[Date] >= MinDate && mDateTable_TRIR[Date] <= MaxDate && YEAR(mDateTable_TRIR[Date]) = 2023 )
        )
    )




TRIR_Dynamic = 
VAR MaxDate = MAX(mDateTable_TRIR[Date])
VAR MinDate = CALCULATE(MaxDate-365)
RETURN
    DIVIDE(
        SUMX(
            FILTER(
                ALL ( mDateTable_TRIR ),
                mDateTable_TRIR[Date] >= MinDate && mDateTable_TRIR[Date] <= MaxDate
            ),
            CALCULATE ( SUM ( Incidents[RecordableCount] ) * 200000 )
        ),
        SUM ( TRIR_Hours[HoursWorked] )
    )
 
 

 TRIR_2022_v2 = CALCULATE(([RecordableIncidents_2022]) * 200000)/[TRIR_TotalHoursWorked]


 Sales R12M =
VAR NumOfMonths = 12
VAR LastCurrentDate =
    MAX ( 'Date'[Date] )
VAR Period =
    DATESINPERIOD ( 'Date'[Date], LastCurrentDate, - NumOfMonths, MONTH )
VAR Result =
    CALCULATE (
        AVERAGEX (
            VALUES ( 'Date'[Calendar Year Month] ),
            [Sales Amount]
        ),
        Period
    )
VAR FirstDateInPeriod = MINX ( Period, 'Date'[Date] )
VAR LastDateWithSales = MAX ( Sales[Order Date] )
RETURN
    IF ( FirstDateInPeriod <= LastDateWithSales, Result )


TRIR_R12M = 
VAR NumOfMonths = 12
VAR LastCurrentDate =
    MAX ( Incidents[Incident Date] )
VAR Period =
    DATESINPERIOD ( Incidents[Incident Date], LastCurrentDate, - NumOfMonths, MONTH )
VAR Result =
    CALCULATE (
        AVERAGEX (
            VALUES ( mDateTable[Year-Month] ),
            Incidents[TotalIncidents]
        ),
        Period
    )
VAR FirstDateInPeriod = MINX ( Period, Incidents[Incident Date] )
VAR LastDateWithSales = MAX ( Incidents[Incident Date] )
RETURN
    IF ( FirstDateInPeriod <= LastDateWithSales, Result )