https://zebrabi.com/guide/how-to-calculate-rolling-12-months-in-power-bi/#:~:text=Step-by-Step%20Guide%20to%20Creating%20a%20Rolling%2012%20Months,Your%20rolling%2012%20months%20calculation%20is%20now%20complete.

Creating a rolling 12 months calculation in Power BI is not as difficult as it may seem. In fact, it can be done in just a few simple steps.

Select 'New Measure' from the 'Modeling' tab in Power BI Desktop.

Enter a name for the measure, such as 'Rolling 12 Months Sales.'

Add the DAX function to calculate the sum of sales data for the past 12 months. The DAX formula for a rolling 12 months calculation is:


Rolling 12 Months Sales = CALCULATE(
    SUM(Sales[Sales Amount]),
    DATESBETWEEN('Calendar'[Date],
    NEXTDAY(SAMEPERIODLASTYEAR('Calendar'[Date])), 
    'Calendar'[Date]))
